package com.wsi.entity;

// Generated May 31, 2015 3:40:50 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Acls generated by hbm2java
 */

@XmlRootElement
public class Acls extends MasterDTO implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9218391803918976631L;
	private String id;
	private Resources resources;
	private Permissions permissions;
	private Groups groups;
	
	public Acls() {
	}

	public Acls(String id, Resources resources, Permissions permissions,
			Groups groups, Date createdAt, Date updatedAt) {
		this.id = id;
		this.resources = resources;
		this.permissions = permissions;
		this.groups = groups;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Acls(String id, Resources resources, Permissions permissions,
			Groups groups, String createdBy, String updatedBy, Date createdAt,
			Date updatedAt) {
		this.id = id;
		this.resources = resources;
		this.permissions = permissions;
		this.groups = groups;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Resources getResources() {
		return this.resources;
	}

	public void setResources(Resources resources) {
		this.resources = resources;
	}

	public Permissions getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Permissions permissions) {
		this.permissions = permissions;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}
}
