package com.wsi.entity;

// Generated May 31, 2015 3:40:50 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Permissions generated by hbm2java
 */
public class Permissions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2094409242685231163L;
	private String id;
	private String name;
	private String createdBy;
	private String updatedBy;
	private Date createdAt;
	private Date updatedAt;
	private Set aclses = new HashSet(0);

	public Permissions() {
	}

	public Permissions(String id, String name, Date createdAt, Date updatedAt) {
		this.id = id;
		this.name = name;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Permissions(String id, String name, String createdBy,
			String updatedBy, Date createdAt, Date updatedAt, Set aclses) {
		this.id = id;
		this.name = name;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.aclses = aclses;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getAclses() {
		return this.aclses;
	}

	public void setAclses(Set aclses) {
		this.aclses = aclses;
	}

}
