package com.wsi.entity;

// Generated May 31, 2015 3:40:50 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductSubCategory generated by hbm2java
 */
public class ProductSubCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4058965075635792887L;
	private String subCatGuid;
	private ProductCategory productCategory;
	private String subCatName;
	private String subCatDesc;
	private String createdBy;
	private String updatedBy;
	private Date createdAt;
	private Date updatedAt;
	private Set productSubCategoryTypes = new HashSet(0);
	private Set postAdds = new HashSet(0);

	public ProductSubCategory() {
	}

	public ProductSubCategory(String subCatGuid, String subCatName,
			String subCatDesc, Date createdAt, Date updatedAt) {
		this.subCatGuid = subCatGuid;
		this.subCatName = subCatName;
		this.subCatDesc = subCatDesc;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ProductSubCategory(String subCatGuid,
			ProductCategory productCategory, String subCatName,
			String subCatDesc, String createdBy, String updatedBy,
			Date createdAt, Date updatedAt, Set productSubCategoryTypes,
			Set postAdds) {
		this.subCatGuid = subCatGuid;
		this.productCategory = productCategory;
		this.subCatName = subCatName;
		this.subCatDesc = subCatDesc;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.productSubCategoryTypes = productSubCategoryTypes;
		this.postAdds = postAdds;
	}

	public String getSubCatGuid() {
		return this.subCatGuid;
	}

	public void setSubCatGuid(String subCatGuid) {
		this.subCatGuid = subCatGuid;
	}

	public ProductCategory getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(ProductCategory productCategory) {
		this.productCategory = productCategory;
	}

	public String getSubCatName() {
		return this.subCatName;
	}

	public void setSubCatName(String subCatName) {
		this.subCatName = subCatName;
	}

	public String getSubCatDesc() {
		return this.subCatDesc;
	}

	public void setSubCatDesc(String subCatDesc) {
		this.subCatDesc = subCatDesc;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getProductSubCategoryTypes() {
		return this.productSubCategoryTypes;
	}

	public void setProductSubCategoryTypes(Set productSubCategoryTypes) {
		this.productSubCategoryTypes = productSubCategoryTypes;
	}

	public Set getPostAdds() {
		return this.postAdds;
	}

	public void setPostAdds(Set postAdds) {
		this.postAdds = postAdds;
	}

}
