package com.wsi.entity;

// Generated May 31, 2015 3:40:50 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductCategory generated by hbm2java
 */
public class ProductCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2107661175822965352L;
	private String catGuid;
	private String catName;
	private String catDesc;
	private String createdBy;
	private String updatedBy;
	private Date createdAt;
	private Date updatedAt;
	private Set productSubCategories = new HashSet(0);

	public ProductCategory() {
	}

	public ProductCategory(String catGuid, String catName, String catDesc,
			Date createdAt, Date updatedAt) {
		this.catGuid = catGuid;
		this.catName = catName;
		this.catDesc = catDesc;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public ProductCategory(String catGuid, String catName, String catDesc,
			String createdBy, String updatedBy, Date createdAt, Date updatedAt,
			Set productSubCategories) {
		this.catGuid = catGuid;
		this.catName = catName;
		this.catDesc = catDesc;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.productSubCategories = productSubCategories;
	}

	public String getCatGuid() {
		return this.catGuid;
	}

	public void setCatGuid(String catGuid) {
		this.catGuid = catGuid;
	}

	public String getCatName() {
		return this.catName;
	}

	public void setCatName(String catName) {
		this.catName = catName;
	}

	public String getCatDesc() {
		return this.catDesc;
	}

	public void setCatDesc(String catDesc) {
		this.catDesc = catDesc;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getProductSubCategories() {
		return this.productSubCategories;
	}

	public void setProductSubCategories(Set productSubCategories) {
		this.productSubCategories = productSubCategories;
	}

}
