package com.wsi.entity;

// Generated May 31, 2015 3:40:50 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4055803596191814717L;
	private String userEmail;
	private Groups groups;
	private String userPasswd;
	private Boolean isRegisterd;
	private String userKey;
	private String createdBy;
	private String updatedBy;
	private Date createdAt;
	private Date updatedAt;
	private Set postAdds = new HashSet(0);
	private UserProfile userProfile;

	public Users() {
	}

	public Users(String userEmail, String userPasswd, Date createdAt,
			Date updatedAt) {
		this.userEmail = userEmail;
		this.userPasswd = userPasswd;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
	}

	public Users(String userEmail, Groups groups, String userPasswd,
			Boolean isRegisterd, String userKey, String createdBy,
			String updatedBy, Date createdAt, Date updatedAt, Set postAdds,
			UserProfile userProfile) {
		this.userEmail = userEmail;
		this.groups = groups;
		this.userPasswd = userPasswd;
		this.isRegisterd = isRegisterd;
		this.userKey = userKey;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.postAdds = postAdds;
		this.userProfile = userProfile;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public Groups getGroups() {
		return this.groups;
	}

	public void setGroups(Groups groups) {
		this.groups = groups;
	}

	public String getUserPasswd() {
		return this.userPasswd;
	}

	public void setUserPasswd(String userPasswd) {
		this.userPasswd = userPasswd;
	}

	public Boolean getIsRegisterd() {
		return this.isRegisterd;
	}

	public void setIsRegisterd(Boolean isRegisterd) {
		this.isRegisterd = isRegisterd;
	}

	public String getUserKey() {
		return this.userKey;
	}

	public void setUserKey(String userKey) {
		this.userKey = userKey;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getPostAdds() {
		return this.postAdds;
	}

	public void setPostAdds(Set postAdds) {
		this.postAdds = postAdds;
	}

	public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}

}
