package com.ami.entity;

// Generated Nov 22, 2014 5:45:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * PostAdd generated by hbm2java
 */
public class PostAdd implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 694399631325856347L;
	private String addGuid;
	private ProductSubCategory productSubCategory;
	private Users users;
	private ProductSubCategoryType productSubCategoryType;
	private String addDesc;
	private int price;
	private Byte negotiable;

	public PostAdd() {
	}

	public PostAdd(String addGuid, ProductSubCategory productSubCategory,
			Users users, ProductSubCategoryType productSubCategoryType,
			String addDesc, int price) {
		this.addGuid = addGuid;
		this.productSubCategory = productSubCategory;
		this.users = users;
		this.productSubCategoryType = productSubCategoryType;
		this.addDesc = addDesc;
		this.price = price;
	}

	public PostAdd(String addGuid, ProductSubCategory productSubCategory,
			Users users, ProductSubCategoryType productSubCategoryType,
			String addDesc, int price, Byte negotiable) {
		this.addGuid = addGuid;
		this.productSubCategory = productSubCategory;
		this.users = users;
		this.productSubCategoryType = productSubCategoryType;
		this.addDesc = addDesc;
		this.price = price;
		this.negotiable = negotiable;
	}

	public String getAddGuid() {
		return this.addGuid;
	}

	public void setAddGuid(String addGuid) {
		this.addGuid = addGuid;
	}

	public ProductSubCategory getProductSubCategory() {
		return this.productSubCategory;
	}

	public void setProductSubCategory(ProductSubCategory productSubCategory) {
		this.productSubCategory = productSubCategory;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public ProductSubCategoryType getProductSubCategoryType() {
		return this.productSubCategoryType;
	}

	public void setProductSubCategoryType(
			ProductSubCategoryType productSubCategoryType) {
		this.productSubCategoryType = productSubCategoryType;
	}

	public String getAddDesc() {
		return this.addDesc;
	}

	public void setAddDesc(String addDesc) {
		this.addDesc = addDesc;
	}

	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public Byte getNegotiable() {
		return this.negotiable;
	}

	public void setNegotiable(Byte negotiable) {
		this.negotiable = negotiable;
	}

}
