package com.ami.entity;

// Generated Nov 22, 2014 5:45:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductSubCategory generated by hbm2java
 */
public class ProductSubCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7635468318095594658L;
	private String subCatGuid;
	private ProductCategory productCategory;
	private String subCatName;
	private String subCatDesc;
	private Set productSubCategoryTypes = new HashSet(0);
	private Set postAdds = new HashSet(0);

	public ProductSubCategory() {
	}

	public ProductSubCategory(String subCatGuid, String subCatName,
			String subCatDesc) {
		this.subCatGuid = subCatGuid;
		this.subCatName = subCatName;
		this.subCatDesc = subCatDesc;
	}

	public ProductSubCategory(String subCatGuid,
			ProductCategory productCategory, String subCatName,
			String subCatDesc, Set productSubCategoryTypes, Set postAdds) {
		this.subCatGuid = subCatGuid;
		this.productCategory = productCategory;
		this.subCatName = subCatName;
		this.subCatDesc = subCatDesc;
		this.productSubCategoryTypes = productSubCategoryTypes;
		this.postAdds = postAdds;
	}

	public String getSubCatGuid() {
		return this.subCatGuid;
	}

	public void setSubCatGuid(String subCatGuid) {
		this.subCatGuid = subCatGuid;
	}

	public ProductCategory getProductCategory() {
		return this.productCategory;
	}

	public void setProductCategory(ProductCategory productCategory) {
		this.productCategory = productCategory;
	}

	public String getSubCatName() {
		return this.subCatName;
	}

	public void setSubCatName(String subCatName) {
		this.subCatName = subCatName;
	}

	public String getSubCatDesc() {
		return this.subCatDesc;
	}

	public void setSubCatDesc(String subCatDesc) {
		this.subCatDesc = subCatDesc;
	}

	public Set getProductSubCategoryTypes() {
		return this.productSubCategoryTypes;
	}

	public void setProductSubCategoryTypes(Set productSubCategoryTypes) {
		this.productSubCategoryTypes = productSubCategoryTypes;
	}

	public Set getPostAdds() {
		return this.postAdds;
	}

	public void setPostAdds(Set postAdds) {
		this.postAdds = postAdds;
	}

}
