package com.ami.entity;

// Generated Nov 22, 2014 5:45:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * ProductSubCategoryType generated by hbm2java
 */
public class ProductSubCategoryType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7057134206240174899L;
	private String typeGuid;
	private ProductSubCategory productSubCategory;
	private String typeName;
	private Set postAdds = new HashSet(0);

	public ProductSubCategoryType() {
	}

	public ProductSubCategoryType(String typeGuid,
			ProductSubCategory productSubCategory, String typeName) {
		this.typeGuid = typeGuid;
		this.productSubCategory = productSubCategory;
		this.typeName = typeName;
	}

	public ProductSubCategoryType(String typeGuid,
			ProductSubCategory productSubCategory, String typeName, Set postAdds) {
		this.typeGuid = typeGuid;
		this.productSubCategory = productSubCategory;
		this.typeName = typeName;
		this.postAdds = postAdds;
	}

	public String getTypeGuid() {
		return this.typeGuid;
	}

	public void setTypeGuid(String typeGuid) {
		this.typeGuid = typeGuid;
	}

	public ProductSubCategory getProductSubCategory() {
		return this.productSubCategory;
	}

	public void setProductSubCategory(ProductSubCategory productSubCategory) {
		this.productSubCategory = productSubCategory;
	}

	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	public Set getPostAdds() {
		return this.postAdds;
	}

	public void setPostAdds(Set postAdds) {
		this.postAdds = postAdds;
	}

}
