package com.ami.entity;

// Generated Nov 22, 2014 5:45:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserProfileId generated by hbm2java
 */
public class UserProfileId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5471278369295725513L;
	private String firstName;
	private String lastName;
	private Long phoneNum;
	private String userEmail;

	public UserProfileId() {
	}

	public UserProfileId(String firstName, String lastName, String userEmail) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.userEmail = userEmail;
	}

	public UserProfileId(String firstName, String lastName, Long phoneNum,
			String userEmail) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.phoneNum = phoneNum;
		this.userEmail = userEmail;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public Long getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(Long phoneNum) {
		this.phoneNum = phoneNum;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserProfileId))
			return false;
		UserProfileId castOther = (UserProfileId) other;

		return ((this.getFirstName() == castOther.getFirstName()) || (this
				.getFirstName() != null && castOther.getFirstName() != null && this
				.getFirstName().equals(castOther.getFirstName())))
				&& ((this.getLastName() == castOther.getLastName()) || (this
						.getLastName() != null
						&& castOther.getLastName() != null && this
						.getLastName().equals(castOther.getLastName())))
				&& ((this.getPhoneNum() == castOther.getPhoneNum()) || (this
						.getPhoneNum() != null
						&& castOther.getPhoneNum() != null && this
						.getPhoneNum().equals(castOther.getPhoneNum())))
				&& ((this.getUserEmail() == castOther.getUserEmail()) || (this
						.getUserEmail() != null
						&& castOther.getUserEmail() != null && this
						.getUserEmail().equals(castOther.getUserEmail())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFirstName() == null ? 0 : this.getFirstName().hashCode());
		result = 37 * result
				+ (getLastName() == null ? 0 : this.getLastName().hashCode());
		result = 37 * result
				+ (getPhoneNum() == null ? 0 : this.getPhoneNum().hashCode());
		result = 37 * result
				+ (getUserEmail() == null ? 0 : this.getUserEmail().hashCode());
		return result;
	}

}
