package com.ami.entity;

// Generated Nov 22, 2014 5:45:05 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5933719903835760406L;
	private UserProfileId id;
	private Users users;

	public UserProfile() {
	}

	public UserProfile(UserProfileId id, Users users) {
		this.id = id;
		this.users = users;
	}

	public UserProfileId getId() {
		return this.id;
	}

	public void setId(UserProfileId id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
