package com.ami.entity;

// Generated Nov 22, 2014 5:45:05 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2020048463084835548L;
	private String userEmail;
	private String userPasswd;
	private Byte isRegisterd;
	private Set postAdds = new HashSet(0);
	private Set userProfiles = new HashSet(0);

	public Users() {
	}

	public Users(String userEmail, String userPasswd) {
		this.userEmail = userEmail;
		this.userPasswd = userPasswd;
	}

	public Users(String userEmail, String userPasswd, Byte isRegisterd,
			Set postAdds, Set userProfiles) {
		this.userEmail = userEmail;
		this.userPasswd = userPasswd;
		this.isRegisterd = isRegisterd;
		this.postAdds = postAdds;
		this.userProfiles = userProfiles;
	}

	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	public String getUserPasswd() {
		return this.userPasswd;
	}

	public void setUserPasswd(String userPasswd) {
		this.userPasswd = userPasswd;
	}

	public Byte getIsRegisterd() {
		return this.isRegisterd;
	}

	public void setIsRegisterd(Byte isRegisterd) {
		this.isRegisterd = isRegisterd;
	}

	public Set getPostAdds() {
		return this.postAdds;
	}

	public void setPostAdds(Set postAdds) {
		this.postAdds = postAdds;
	}

	public Set getUserProfiles() {
		return this.userProfiles;
	}

	public void setUserProfiles(Set userProfiles) {
		this.userProfiles = userProfiles;
	}

}
