package com.ami.filter;

import org.apache.commons.lang.RandomStringUtils;

import com.sun.jersey.core.header.InBoundHeaders;
import com.sun.jersey.spi.container.ContainerRequest;
import com.sun.jersey.spi.container.ContainerResponse;
import com.sun.jersey.spi.container.ContainerResponseFilter;
 
public class ResponseCorsFilter implements ContainerResponseFilter {
 
    @Override
    public ContainerResponse filter(ContainerRequest req, ContainerResponse contResp) {
 
    	// code which i copied from net(simpleAPI)
      /*  ResponseBuilder resp = Response.fromResponse(contResp.getResponse());
        resp.header("Access-Control-Allow-Origin", "*")
                .header("Access-Control-Allow-Methods", "GET, POST, OPTIONS , PUT , DELETE");
 
        String reqHead = req.getHeaderValue("Access-Control-Request-Headers");
 
        if(null != reqHead && !reqHead.equals("")){
            resp.header("Access-Control-Allow-Headers", reqHead);
            resp.header("x-powered-by", "my olx system");
        }
 
        contResp.setResponse(resp.build());
            return contResp;*/
    	
    	 String rts = req.getHeaderValue("x-my-request-id");
         String requestToken = ((rts != null)  ? rts : "");

         // if we don't get any requestId, then generate random string and
         // prefix it with 'AFN_' to convey its generated by AppFoundation
         if (requestToken.isEmpty()) {
           requestToken = "MY_" + RandomStringUtils.randomAlphanumeric(9);
           System.out.println("inside the adding header code");
          /* List<String> rts1 = new ArrayList<String>();
           rts1.add(requestToken);
           Map<String, List<String>> header = new HashMap<String,  List<String>>();
           header.put("x-my-request-id", rts1);*/
          // req.setHeaders(header);
           InBoundHeaders headers = new InBoundHeaders();
           headers.add("x-my-request-id", requestToken);
           //contResp.setHeaders(headers);
           contResp.getHttpHeaders().add("x-my-request-id", requestToken);
         }
         
    	if(contResp.getHttpHeaders().get("Access-Control-Allow-Origin")==null)
    		contResp.getHttpHeaders().add("Access-Control-Allow-Origin", "*");
    		
    		contResp.getHttpHeaders().add("Access-Control-Allow-Headers", 
    			"origin," +
    			"content-type," +
    			"accept," +
    			"authorization,"+
    			"if-modified-since," +
    			"pragma," +
    			"cache-control");
    		contResp.getHttpHeaders().add("Access-Control-Allow-Credentials", "true");
    		contResp.getHttpHeaders().add("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS, HEAD");
    		contResp.getHttpHeaders().add("Access-Control-Max-Age", "1209600");
    		return contResp;
    }
 
}